version: '3'
services:
  airflow:
    build: .
    restart: always
    volumes:
      - ./airflow.cfg:/home/phendy/airflow/airflow.cfg
      - ./dags:/home/phendy/airflow/dags
      - ./logs:/home/phendy/airflow/logs
      - ./plugins:/home/phendy/airflow/plugins
      - /home/phendy/Downloads/intrepid-period-422622-n5-4b46f2a8737b.json:/home/phendy/Downloads/intrepid-period-422622-n5-4b46f2a8737b.json
    ports:
      - "8080:8080"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
